### ISSUE TITLE
你好，我是 `dev-sidecar` 的 committer，我在DS里使用了你们的白名单，特来感谢

### ISSUE THREAD

**Issue by wangliang181230** [pluwen/china-domain-allowlist#26]
你好，我是 `dev-sidecar` 的 committer，我在DS里使用了你们的白名单，特来感谢。
如果DS有违反你们协议的地方，还请指出，我们会积极配合调整。

我们的仓库：https://github.com/docmirror/dev-sidecar
合并的PR：https://github.com/docmirror/dev-sidecar/pull/366

谢谢。

**Comment by pluwen** [comment]
没事

**Comment by MulatramAwA** [comment]
围观大佬
